name: 'CI'
description: 'Clone the user of the dependency, change its build.zig.zon and test its update option'
inputs:
  user:
    description: 'User of the dependency'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2.2.0
      with:
        version: 0.12.0-dev.3630+215de3ee6

    - name: Install packages
      shell: bash
      run: |
        sudo apt-get install -y libwayland-bin

    - name: Set variables
      id: vars
      shell: bash
      run: |
        printf 'tmp=%s\n' "$(mktemp -d)" >> ${GITHUB_OUTPUT}
        printf 'hash=%s\n' "$(zig fetch .)" >> ${GITHUB_OUTPUT}

    - name: Clone ${{ inputs.user }}.zig
      shell: bash
      run: |
        git clone "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY_OWNER}/${{ inputs.user }}.zig.git" ${{ steps.vars.outputs.tmp }}

    - name: Prepare ${{ inputs.user }}.zig/build.zig.zon
      working-directory: ${{ steps.vars.outputs.tmp }}
      shell: bash
      run: |
        zon_url="$(grep -o "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/archive/.*\.tar\.gz" build.zig.zon)"
        zon_hash="$(zig fetch "${zon_url}")"
        sed -i "s@${zon_url}@${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/archive/${GITHUB_SHA}.tar.gz@;
                s@${zon_hash}@${{ steps.vars.outputs.hash }}@" build.zig.zon

    - name: Build ${{ inputs.user }}.zig
      working-directory: ${{ steps.vars.outputs.tmp }}
      shell: bash
      run:
        zig build -Dupdate
