name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  test:
    strategy:
      matrix:
        repo:
          - dep: toolbox
            user: vulkan.zig
          - dep: toolbox
            user: wayland.zig
          - dep: toolbox
            user: X11.zig
          - dep: toolbox
            user: glfw.zig
          - dep: toolbox
            user: cimgui.zig
          - dep: toolbox
            user: spirv.zig
          - dep: toolbox
            user: glslang.zig
          - dep: toolbox
            user: shaderc.zig
          - dep: vulkan.zig
            user: glfw.zig
          - dep: wayland.zig
            user: glfw.zig
          - dep: X11.zig
            user: glfw.zig
          - dep: glfw.zig
            user: cimgui.zig
          - dep: cimgui.zig
            user: spaceporn
          - dep: spirv.zig
            user: shaderc.zig
          - dep: glslang.zig
            user: shaderc.zig
          - dep: shaderc.zig
            user: spaceporn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo.dep }}"

    - name: Prepare CI
      id: prepare
      run: |
        sha="$(git rev-parse HEAD)"
        printf 'sha=%s\n' "${sha}" >> "${GITHUB_OUTPUT}"

    - uses: actions/checkout@v4
    - uses: ./
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo.dep }}"
        sha: "${{ steps.prepare.outputs.sha }}"
        user: "${{ matrix.repo.user }}"
        token: "${{ github.token }}"
        test_build: ${{ matrix.repo.user == 'spaceporn' && 'true' || 'false' }}
        test_update: ${{ matrix.repo.user == 'spaceporn' && 'false' || 'true' }}
        test_fetch: ${{ matrix.repo.user == 'spaceporn' && 'false' || 'true' }}
    - uses: actions/checkout@v4
