name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  test:
    strategy:
      matrix:
        repo:
          - user: vulkan.zig
            dep: toolbox
          - user: wayland.zig
            dep: toolbox
          - user: X11.zig
            dep: toolbox
          - user: glfw.zig
            dep: toolbox
          - user: glfw.zig
            dep: vulkan.zig
          - user: glfw.zig
            dep: wayland.zig
          - user: glfw.zig
            dep: X11.zig
          - user: cimgui.zig
            dep: toolbox
          - user: cimgui.zig
            dep: glfw.zig
          - user: spirv.zig
            dep: toolbox
          - user: glslang.zig
            dep: toolbox
          - user: shaderc.zig
            dep: toolbox
          - user: shaderc.zig
            dep: spirv.zig
          - user: shaderc.zig
            dep: glslang.zig
          - user: spaceporn
            dep: cimgui.zig
          - user: spaceporn
            dep: shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ format ('{0}/{1}', github.repository_owner, matrix.repo.dep) }}"

    - name: Prepare CI
      id: prepare
      run: |
        printf 'sha=%s\n' "$(git rev-parse HEAD)" >> "${{ GITHUB_OUTPUT }}"

    - uses: tiawl/spaceporn-dep-action-ci@ci
      with:
        repository: "${{ format ('{0}/{1}', github.repository_owner, matrix.repo.dep) }}"
        sha: "${{ steps.prepare.outputs.sha }}"
        user: "${{ matrix.repo.user }}"
        test_build: ${{ matrix.repo.user == 'spaceporn' && 'true' || 'false' }}
        test_update: ${{ matrix.repo.user == 'spaceporn' && 'false' || 'true' }}
        test_fetch: ${{ matrix.repo.user == 'spaceporn' && 'false' || 'true' }}
