name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  test-cimgui:
    strategy:
      matrix:
        dep:
          - toolbox
          - glfw.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.dep }}"

    - name: Prepare CI
      id: prepare
      run: |
        sha="$(git rev-parse HEAD)"
        printf 'sha=%s\n' "${sha}" >> "${GITHUB_OUTPUT}"

    - uses: actions/checkout@v4
    - uses: ./
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.dep }}"
        additional_zig_opts: '-Dplatform=GLFW -Drenderer=Vulkan'
        sha: "${{ steps.prepare.outputs.sha }}"
        user: 'cimgui.zig'
        token: "${{ github.token }}"
        test_build: 'false'
        test_update: 'true'
        test_fetch: 'true'
    - uses: actions/checkout@v4
  test-spaceporn:
    strategy:
      matrix:
        dep:
          - cimgui.zig
          - shaderc.zig
        os:
          - ubuntu-latest
          - windows-latest
        zig_opts:
          - ''
          - '-Ddev'
          - '-Dturbo'
    runs-on: "${{ matrix-os }}"
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.dep }}"

    - name: Prepare CI
      id: prepare
      run: |
        sha="$(git rev-parse HEAD)"
        printf 'sha=%s\n' "${sha}" >> "${GITHUB_OUTPUT}"

    - uses: actions/checkout@v4
    - uses: ./
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.dep }}"
        sha: "${{ steps.prepare.outputs.sha }}"
        user: 'spaceporn'
        token: "${{ github.token }}"
        test_build: 'true'
        test_update: 'false'
        test_fetch: 'false'
    - uses: actions/checkout@v4
  test:
    strategy:
      matrix:
        repo:
          - dep: toolbox
            user: vulkan.zig
          - dep: toolbox
            user: wayland.zig
          - dep: toolbox
            user: X11.zig
          - dep: toolbox
            user: glfw.zig
          - dep: toolbox
            user: spirv.zig
          - dep: toolbox
            user: glslang.zig
          - dep: toolbox
            user: shaderc.zig
          - dep: vulkan.zig
            user: glfw.zig
          - dep: wayland.zig
            user: glfw.zig
          - dep: X11.zig
            user: glfw.zig
          - dep: spirv.zig
            user: shaderc.zig
          - dep: glslang.zig
            user: shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo.dep }}"

    - name: Prepare CI
      id: prepare
      run: |
        sha="$(git rev-parse HEAD)"
        printf 'sha=%s\n' "${sha}" >> "${GITHUB_OUTPUT}"

    - uses: actions/checkout@v4
    - uses: ./
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo.dep }}"
        sha: "${{ steps.prepare.outputs.sha }}"
        user: "${{ matrix.repo.user }}"
        token: "${{ github.token }}"
        test_build: 'false'
        test_update: 'true'
        test_fetch: 'true'
    - uses: actions/checkout@v4
